name: API Endpoint Testing Workflow

on:
  workflow_run:
    workflows: ["Build Server"]
    types:
      - completed

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Test EchoResponseHandler
      run: |
        sleep 5  

        response=$(curl -s "http://127.0.0.1:8080/echo=cat")

        if [[ "$response" == *"cat"* ]]; then
          echo "Test passed: EchoResponseHandler returned the expected input."
        else
          echo "Test failed: EchoResponseHandler did not return the expected input."
          exit 1
        fi

    - name: Stop the server
      run: pkill -f "build/main.go" || true   
